### ISSUE TITLE
Duplicate Trips in view due to duplicate drivestate with same EndPos

### ISSUE THREAD

**Issue by flosoft** [bassmaster187/TeslaLogger#780]
**Logfile**
```
11.04.2022 21:00:02 : TeslaLogger process statistics
11.04.2022 21:00:04 : #1: IsDriving = NULL!
11.04.2022 21:00:16 : #1: isCharging = NULL
11.04.2022 21:00:20 : #1: isCharging = NULL
11.04.2022 21:00:25 : #1: isCharging = NULL
11.04.2022 21:00:27 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:00:37 : #1: IsDriving = NULL!
11.04.2022 21:00:42 : #1: IsDriving = NULL!
11.04.2022 21:01:50 : #1: IsDriving = NULL!
11.04.2022 21:07:26 : #1: IsDriving = NULL!
11.04.2022 21:09:49 : #1: IsDriving = NULL!
11.04.2022 21:11:23 : #1: IsDriving = NULL!
11.04.2022 21:18:09 : #1: ShiftStateChange: D -> R
11.04.2022 21:18:13 : #1: ShiftStateChange: D -> R
11.04.2022 21:18:26 : #1: ShiftStateChange: R -> D
11.04.2022 21:18:26 : #1: ShiftStateChange: R -> D
11.04.2022 21:18:43 : #1: ShiftStateChange: D -> P
11.04.2022 21:18:43 : #1: ShiftStateChange: D -> P
11.04.2022 21:18:47 : #1: ShiftStateChange: D -> P
11.04.2022 21:18:49 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:18:49 : #1: Request StopStreaming
11.04.2022 21:18:49 : #1: GetAvgConsumption: sumkm:2401.6 avgkm:171.5 kwh/100km:19.9 avgsocdiff:42.7 maxkm:406.7
11.04.2022 21:18:49 : #1: ScanMyTesla FastMode: False
11.04.2022 21:18:49 : #1: ShareData: SendAllChargingData start
11.04.2022 21:18:49 : #1: ShareData: SELECT chargingstate ms: 4
11.04.2022 21:18:50 : #1: ShareData: Insert OK:159333
11.04.2022 21:18:50 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:18:50 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:18:50 : #1: Request StopStreaming
11.04.2022 21:18:50 : #1: GetAvgConsumption: sumkm:2401.6 avgkm:171.5 kwh/100km:19.9 avgsocdiff:42.7 maxkm:406.7
11.04.2022 21:18:50 : #1: ScanMyTesla FastMode: False
11.04.2022 21:18:50 : #1: ShareData: SendAllChargingData start
11.04.2022 21:18:50 : #1: ShareData: SELECT chargingstate ms: 4
11.04.2022 21:18:50 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:18:54 : UpdateTripElevation (Task) start:48407 end:50194
11.04.2022 21:18:56 : GeocodeCache:Insert
11.04.2022 21:18:56 : Reverse geocoding by Nominatim64
11.04.2022 21:18:56 : UpdateTripElevation ID:48657
11.04.2022 21:18:56 : Column 'lat, lng' is constrained to be unique.  Value '41.417535, 2.224563' is already present.
11.04.2022 21:18:56 : Reverse geocoding by Nominatim65
11.04.2022 21:18:57 : UpdateTripElevation ID:48908
11.04.2022 21:18:58 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:18:58 : #1: Request StopStreaming
11.04.2022 21:18:58 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:18:58 : #1: ScanMyTesla FastMode: False
11.04.2022 21:18:58 : #1: ShareData: SendAllChargingData start
11.04.2022 21:18:58 : #1: ShareData: SELECT chargingstate ms: 4
11.04.2022 21:18:58 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:18:58 : Reverse geocoding by GeocodeCache
11.04.2022 21:18:58 : UpdateTripElevation ID:49159
11.04.2022 21:18:59 : UpdateTripElevation ID:49410
11.04.2022 21:19:00 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:19:01 : UpdateTripElevation ID:49661
11.04.2022 21:19:02 : UpdateTripElevation ID:49912
11.04.2022 21:19:03 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:19:03 : UpdateTripElevation ID:50163
11.04.2022 21:19:03 : UpdateTripElevation finished start:48407 end:50194
11.04.2022 21:19:03 : #1: UpdateDriveHeightStatistics(278): 1 rows updated
11.04.2022 21:19:04 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:19:20 : Checking TeslaLogger online update (current version: 1.52.5.0) ...
11.04.2022 21:19:20 : TeslaLogger is up to date (current version: 1.52.5.0, latest version online: 1.52.5.0, update policy: all)
11.04.2022 21:19:25 : #1: IsDriving = NULL!
11.04.2022 21:22:54 : #1: isCharging = NULL
11.04.2022 21:23:11 : #1: isCharging = NULL
11.04.2022 21:24:25 : #1: change TeslaLogger state: Online -> Start
11.04.2022 21:24:32 : #1: Reason:is_user_present prevents car to get sleep
11.04.2022 21:24:37 : #1: ScanMyTesla FastMode: False
11.04.2022 21:24:37 : Reverse geocoding by GeocodeCache
11.04.2022 21:24:39 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:24:49 : #1: change TeslaLogger state: Online -> Start
11.04.2022 21:25:05 : #1: Reason:is_user_present prevents car to get sleep
11.04.2022 21:25:06 : #1: ShiftStateChange: P -> R
11.04.2022 21:25:10 : #1: ScanMyTesla FastMode: False
11.04.2022 21:25:11 : #1: ShiftStateChange: P -> D
11.04.2022 21:25:12 : #1: ScanMyTesla FastMode: True
11.04.2022 21:25:12 : #1: Missing: 0.0130003057752219 km
11.04.2022 21:25:16 : GeocodeCache:Insert
11.04.2022 21:25:16 : Reverse geocoding by Nominatim66
11.04.2022 21:25:17 : #1: change TeslaLogger state: Online -> Drive
11.04.2022 21:25:17 : CombineChangingStates start
11.04.2022 21:25:17 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:25:17 : CombineChangingStates took 4ms
11.04.2022 21:25:17 : GeocodeCache:Insert
11.04.2022 21:25:17 : Reverse geocoding by Nominatim67
11.04.2022 21:25:18 : #1: ScanMyTesla FastMode: True
11.04.2022 21:25:18 : #1: Missing: 0.024000193120628 km
11.04.2022 21:25:21 : #1: ShiftStateChange: P -> D
11.04.2022 21:25:21 : #1: ShiftStateChange: R -> D
11.04.2022 21:25:23 : #1: change TeslaLogger state: Online -> Drive
11.04.2022 21:25:23 : CombineChangingStates start
11.04.2022 21:25:23 : CombineChangingStates took 4ms
11.04.2022 21:25:23 : GeocodeCache:Insert
11.04.2022 21:25:23 : Reverse geocoding by Nominatim68
11.04.2022 21:25:39 : #1: ScanMyTesla FastMode: True
11.04.2022 21:25:39 : #1: Missing: 0.180000643737912 km
11.04.2022 21:25:44 : #1: change TeslaLogger state: Online -> Drive
11.04.2022 21:25:44 : CombineChangingStates start
11.04.2022 21:25:44 : CombineChangingStates took 8ms
11.04.2022 21:25:45 : GeocodeCache:Insert
11.04.2022 21:25:45 : Reverse geocoding by Nominatim69
11.04.2022 21:28:42 : #1: IsDriving = NULL!
11.04.2022 21:32:08 : #1: isCharging = NULL
11.04.2022 21:32:09 : #1: isCharging = NULL
11.04.2022 21:32:18 : #1: Result.Statuscode: 404 (NotFound) cmd: charge_state Retry: 1
11.04.2022 21:32:19 : #1: isCharging = NULL
11.04.2022 21:32:29 : #1: IsDriving = NULL!
11.04.2022 21:32:30 : #1: IsDriving = NULL!
11.04.2022 21:32:40 : #1: IsDriving = NULL!
11.04.2022 21:33:00 : #1: IsDriving = NULL!
11.04.2022 21:33:16 : #1: isCharging = NULL
11.04.2022 21:33:21 : #1: isCharging = NULL
11.04.2022 21:33:37 : #1: IsDriving = NULL!
11.04.2022 21:33:44 : #1: IsDriving = NULL!
11.04.2022 21:34:04 : #1: IsDriving = NULL!
11.04.2022 21:34:05 : #1: isCharging = NULL
11.04.2022 21:34:05 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:34:16 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:34:16 : #1: IsDriving = NULL!
11.04.2022 21:34:25 : #1: Result.Statuscode: 404 (NotFound) cmd: charge_state Retry: 1
11.04.2022 21:34:26 : #1: IsDriving = NULL!
11.04.2022 21:34:26 : #1: isCharging = NULL
11.04.2022 21:34:37 : #1: isCharging = NULL
11.04.2022 21:34:37 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:34:42 : #1: ShiftStateChange: D -> R
11.04.2022 21:34:54 : #1: IsDriving = NULL!
11.04.2022 21:34:57 : #1: ShiftStateChange: D -> R
11.04.2022 21:35:08 : #1: IsDriving = NULL!
11.04.2022 21:35:14 : #1: ShiftStateChange: D -> R
11.04.2022 21:35:24 : #1: ShiftStateChange: R -> P
11.04.2022 21:35:29 : #1: ShiftStateChange: R -> P
11.04.2022 21:35:32 : #1: ShiftStateChange: R -> P
11.04.2022 21:35:34 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:35:34 : #1: Request StopStreaming
11.04.2022 21:35:34 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:35:34 : #1: ScanMyTesla FastMode: False
11.04.2022 21:35:34 : #1: ShareData: SendAllChargingData start
11.04.2022 21:35:34 : #1: ShareData: SELECT chargingstate ms: 4
11.04.2022 21:35:34 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:35:34 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:35:34 : Reverse geocoding by Geofence
11.04.2022 21:35:34 : UpdateTripElevation (Task) start:50203 end:50338
11.04.2022 21:35:35 : UpdateTripElevation finished start:50203 end:50338
11.04.2022 21:35:35 : #1: UpdateDriveHeightStatistics(281): 1 rows updated
11.04.2022 21:35:37 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:35:37 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:35:37 : #1: Request StopStreaming
11.04.2022 21:35:37 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:35:37 : #1: ScanMyTesla FastMode: False
11.04.2022 21:35:37 : #1: ShareData: SendAllChargingData start
11.04.2022 21:35:37 : #1: ShareData: SELECT chargingstate ms: 0
11.04.2022 21:35:37 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:35:37 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:35:37 : Reverse geocoding by Geofence
11.04.2022 21:35:39 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:35:42 : #1: change TeslaLogger state: Drive -> Start
11.04.2022 21:35:42 : #1: Request StopStreaming
11.04.2022 21:35:42 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:35:42 : #1: ScanMyTesla FastMode: False
11.04.2022 21:35:42 : #1: ShareData: SendAllChargingData start
11.04.2022 21:35:42 : #1: ShareData: SELECT chargingstate ms: 4
11.04.2022 21:35:42 : #1: ShareData: SendAllChargingData finished
11.04.2022 21:35:42 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:35:42 : Reverse geocoding by Geofence
11.04.2022 21:35:44 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:37:03 : #1: IsDriving = NULL!
11.04.2022 21:37:05 : #1: IsDriving = NULL!
11.04.2022 21:37:07 : #1: IsDriving = NULL!
11.04.2022 21:37:24 : #1: isCharging = NULL
11.04.2022 21:37:26 : #1: isCharging = NULL
11.04.2022 21:37:28 : #1: isCharging = NULL
11.04.2022 21:38:15 : #1: IsDriving = NULL!
11.04.2022 21:38:17 : #1: IsDriving = NULL!
11.04.2022 21:38:18 : #1: IsDriving = NULL!
11.04.2022 21:38:37 : #1: isCharging = NULL
11.04.2022 21:38:38 : #1: isCharging = NULL
11.04.2022 21:38:39 : #1: isCharging = NULL
11.04.2022 21:38:48 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:38:49 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:38:50 : #1: GetOutsideTempAsync: NULL
11.04.2022 21:39:51 : #1: change TeslaLogger state: Online -> Start
11.04.2022 21:39:51 : #1: Request StopStreaming
11.04.2022 21:39:51 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:39:51 : #1: change TeslaLogger state: Online -> Start
11.04.2022 21:39:51 : #1: Request StopStreaming
11.04.2022 21:39:51 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:39:51 : #1: ScanMyTesla FastMode: False
11.04.2022 21:39:51 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:39:51 : Reverse geocoding by Geofence
11.04.2022 21:39:52 : #1: ScanMyTesla FastMode: False
11.04.2022 21:39:52 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:39:52 : Reverse geocoding by Geofence
11.04.2022 21:39:53 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:39:53 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:39:56 : #1: change TeslaLogger state: Online -> Start
11.04.2022 21:39:56 : #1: Request StopStreaming
11.04.2022 21:39:56 : #1: GetAvgConsumption: sumkm:2993.8 avgkm:176.1 kwh/100km:20.1 avgsocdiff:44.4 maxkm:401.9
11.04.2022 21:39:57 : #1: ScanMyTesla FastMode: False
11.04.2022 21:39:57 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:39:57 : Reverse geocoding by Geofence
11.04.2022 21:39:58 : #1: change TeslaLogger state: Start -> Online
11.04.2022 21:41:05 : #1: isCharging = NULL
11.04.2022 21:41:08 : #1: IsDriving = NULL!
11.04.2022 21:41:11 : #1: IsDriving = NULL!
11.04.2022 21:41:44 : #1: Charging! Voltage: 234V / Power: 0kW / Timestamp: 1649706103941 / Date: 2022-04-11 21:41:43
11.04.2022 21:41:48 : #1: Charging! Voltage: 231V / Power: 1kW / Timestamp: 1649706108202 / Date: 2022-04-11 21:41:48
11.04.2022 21:41:48 : #1: Charging
11.04.2022 21:41:48 : #1: ScanMyTesla FastMode: True
11.04.2022 21:41:52 : #1: Charging! Voltage: 219V / Power: 4kW / Timestamp: 1649706111970 / Date: 2022-04-11 21:41:51
11.04.2022 21:41:52 : #1: Charging
11.04.2022 21:41:52 : #1: ScanMyTesla FastMode: True
11.04.2022 21:41:57 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:41:57 : Reverse geocoding by Geofence
11.04.2022 21:41:57 : #1: change TeslaLogger state: Online -> Charge
11.04.2022 21:42:02 : #1: Charging! Voltage: 218V / Power: 4kW / Timestamp: 1649706121107 / Date: 2022-04-11 21:42:01
11.04.2022 21:42:02 : #1: Charging
11.04.2022 21:42:02 : #1: ScanMyTesla FastMode: True
11.04.2022 21:42:02 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:42:02 : Reverse geocoding by Geofence
11.04.2022 21:42:02 : #1: change TeslaLogger state: Online -> Charge
11.04.2022 21:42:12 : Distance: 13.7579858636436 - Radius: 50 - ?? Parking B:SM biotech
11.04.2022 21:42:12 : Reverse geocoding by Geofence
11.04.2022 21:42:12 : #1: change TeslaLogger state: Online -> Charge
11.04.2022 21:42:27 : #1: StartChargingState Task start
11.04.2022 21:42:27 : #1: StartChargingState Task latestPos: 50349
11.04.2022 21:42:28 : #1: isCharging = NULL
11.04.2022 21:42:32 : #1: StartChargingState Task start
11.04.2022 21:42:32 : #1: StartChargingState Task latestPos: 50349
11.04.2022 21:42:35 : #1: StartChargingState Task newPos: 50350
11.04.2022 21:42:35 : #1: StartChargingState Task (poslng, poslat, chglng, chglat) (2.1944, 41.38536, 2.1944, 41.38536)
11.04.2022 21:42:35 : #1: StartChargingState Task distance: 0
11.04.2022 21:42:41 : #1: StartChargingState Task newPos: 50351
11.04.2022 21:42:41 : #1: StartChargingState Task (poslng, poslat, chglng, chglat) (2.1944, 41.38536, 2.1944, 41.38536)
11.04.2022 21:42:41 : #1: StartChargingState Task distance: 0
11.04.2022 21:42:42 : #1: StartChargingState Task start
11.04.2022 21:42:42 : #1: StartChargingState Task latestPos: 50351
11.04.2022 21:42:51 : #1: StartChargingState Task newPos: 50352
11.04.2022 21:42:51 : #1: StartChargingState Task (poslng, poslat, chglng, chglat) (2.1944, 41.38536, 2.1944, 41.38536)
11.04.2022 21:42:51 : #1: StartChargingState Task distance: 0
11.04.2022 21:44:36 : #1: isCharging = NULL
11.04.2022 21:50:54 : #1: isCharging = NULL
11.04.2022 21:50:54 : #1: isCharging = NULL
11.04.2022 21:56:01 : #1: isCharging = NULL
11.04.2022 21:57:17 : #1: isCharging = NULL
11.04.2022 21:58:31 : #1: isCharging = NULL
```

**Describe the bug**
For one day, TeslaLogger duplicated my trips 2-3 times with a slightly varying StartPos but same EndPos.
Looking at the `drivestate` table, I can see that the initial (biggest delta between `StartPos` and `EndPos`) `drivestate` has values in the following columns, the others do not: `outside_temp_avg, speed_max, power_max, power_min, power_avg`
All other values seem to be calculated.

Here's a full DB example overlapping with the log times above:

CSV:
```
id,StartDate,StartPos,EndDate,EndPos,outside_temp_avg,speed_max,power_max,power_min,power_avg,meters_up,meters_down,distance_up_km,distance_down_km,distance_flat_km,height_max,height_min,CarID
283,2022-04-11 21:25:39,50210,2022-04-11 21:35:20,50338,,,,,,68,65,2.72800746738,1.47899962984,1.93800473148,16,5,1
282,2022-04-11 21:25:18,50204,2022-04-11 21:35:20,50338,,,,,,69,68,2.71200733863,1.49199993562,2.09700500507,16,5,1
281,2022-04-11 21:25:12,50203,2022-04-11 21:35:20,50338,15,122,378,-99,6.8897,69,68,2.71200733863,1.49199993562,2.10800489242,16,5,1
```

Markdown:

| id  | StartDate           | StartPos | EndDate             | EndPos | outside_temp_avg | speed_max | power_max | power_min | power_avg | meters_up | meters_down | distance_up_km | distance_down_km | distance_flat_km | height_max | height_min | CarID |
|-----|---------------------|----------|---------------------|--------|------------------|-----------|-----------|-----------|-----------|-----------|-------------|----------------|------------------|------------------|------------|------------|-------|
| 283 | 2022-04-11 21:25:39 | 50210    | 2022-04-11 21:35:20 | 50338  |                  |           |           |           |           | 68        | 65          | 2.72800746738  | 1.47899962984    | 1.93800473148    | 16         | 5          | 1     |
| 282 | 2022-04-11 21:25:18 | 50204    | 2022-04-11 21:35:20 | 50338  |                  |           |           |           |           | 69        | 68          | 2.71200733863  | 1.49199993562    | 2.09700500507    | 16         | 5          | 1     |
| 281 | 2022-04-11 21:25:12 | 50203    | 2022-04-11 21:35:20 | 50338  | 15               | 122       | 378       | -99       | 6.8897    | 69        | 68          | 2.71200733863  | 1.49199993562    | 2.10800489242    | 16         | 5          | 1     |

As mentioned above, this occurred with all trips on that day in a similar fashion.

**To Reproduce**
Unknown.

**Expected behavior**
There should not be any overlapping entries in `drivestate` resulting in duplicate trips.

**Screenshots**
`drivestate` table:
<img width="1331" alt="163268149-73ef003f-5304-4e73-8f6d-8c60941a550f" src="https://user-images.githubusercontent.com/602633/163269411-7c4c8c30-0607-45e7-b05c-d3eb277a2bff.png">

Trip List showing duplicate trips:
![9cf1d25026fc17fc9e87842dac70f801f1bddd44](https://user-images.githubusercontent.com/602633/163268750-cb6389e8-9dc0-4f9a-a481-a203f52cb321.png)

**Teslalogger Type**
- Docker
- Teslalogger 1.52.5.0
- IP at the time: 62.83.127.XXX
- No ScanMyTesla

**Do you use Tasker or iBeacon**
No

**Comment by superfloh247** [comment]
I have the same problem and an idea where it comes from.
Just restart TeslaLogger for now, that should solve it for some days

**Comment by RetoHB** [comment]
I have the same issue. Restarting Teslalogger does not solve it, not even for a few days. In addition to this, some of my trips get divided into several parts, even though the car never was put in "P". Perhaps wrong DriveStates from the Tesla Server?

**Comment by superfloh247** [comment]
fresh token from the Tesla auth app and TL restart fixed it for me

**Comment by flosoft** [comment]
So, new tokens seems to have fixed it for now - can I just go ahead and delete the incorrect `drivestate` entries?

**Comment by bassmaster187** [comment]
EDIT: Query updated to take account for multiply cars in one database and better performance

**Comment by flosoft** [comment]
Executed the query. After checking the trips table now it all looks good.

**Comment by rsnbrgj** [comment]
Yep, the query does the clean up apparently. Good solution until a permanent fix will be available.
